name: flutter_mobile_template
description: "Flutter Mobile Project Template"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  dio: ^5.5.0+1
  flutter_guid: ^0.3.1
  json_annotation: ^4.9.0
  envied: ^0.5.4+1
  go_router: ^14.2.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_signin_button: ^2.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  font_awesome_flutter: ^9.2.0
  supabase_flutter: ^2.6.0
  google_sign_in: ^6.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/splash.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.11
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
